=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/defines/xml/component.config.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/component.config.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE config SYSTEM "component.config.dtd">

    <config>
    ...
    </config>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT config (defaultTask|tasks)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT defaultTask EMPTY>
<!ATTLIST defaultTask
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tasks (task)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT task EMPTY>
<!ATTLIST task
    name CDATA #IMPLIED
    default CDATA #IMPLIED
    label CDATA #IMPLIED
  >

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/hlimit/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/component.config.dtd">
<config>
	<defaultTask value="add" />
	<tasks>
		<task name="add" default="1" label="add" />
		<task name="edit" default="1" label="edit" />
		<task name="delete" default="1" label="delete" />
		<task name="generation" default="1" label="confirm" />
		<task name="periodedit" default="1" label="Period Edit" />
		<task name="trigger_holidays_cron" default="1" label="TRIGGER_HOLIDAYS_CRON" />
		<task name="nextgeneration" default="1" label="nextgeneration" />
	</tasks>
	<allowTasks>
		<task name="cancel" default="1" label="cancel" />
		<task name="save" default="1" label="save" />
	</allowTasks>
</config>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/hrtable/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/component.config.dtd">
<config>
    <defaultTask value="add" />
    <tasks>
        <task name="delete" default="1" label="delete" />
    </tasks>
    <allowTasks>
        <task name="add" default="1" label="add" />
        <task name="cancel" default="1" label="cancel" />
        <task name="save" default="1" label="save" />
        <task name="generate" default="1" label="generate" />
        <task name="send" default="1" label="send" />
        <task name="edit" default="1" label="edit" />
        <task name="approve" default="1" label="approve" />
        <task name="do" default="1" label="do" />
    </allowTasks>
</config>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/s/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/component.config.dtd">
<config>
	<defaultTask value="getworkers" />
	<tasks>
		<task name="getchiefs" default="1" label="getchiefs" />
		<task name="gettimedata" default="1" label="gettimedata" />
		<task name="getworkers" default="1" label="getworkers" />
		<task name="getworker" default="1" label="getworker" />
		<task name="roleaudit" default="1" label="roleaudit" />
		<task name="savecelldata" default="1" label="savecelldata" />
		<!--<task name="getreworkers" default="1" label="getReWorkers" />-->
		<task name="ajaxworkers" default="1" label="ajaxworkers" />
		<task name="direct_subordianate_tree" default="1" label="direct_subordianate_tree" />
		<task name="additional_subordianate_tree" default="1" label="additional_subordianate_tree" />
	</tasks>
	<allowTasks>
		<task name="getgworkers" default="1" label="getgworkers" />
		<task name="ajaxchiefs" default="1" label="ajaxchiefs" />
		<task name="getuworkers" default="1" label="getuworkers" />
		<task name="ajaxuniqworkers" default="1" label="ajaxuniqworkers" />
		<task name="ajaxchiefworkers" default="1" label="ajaxchiefworkers" />
		<task name="ajaxchiefsworkers" default="1" label="ajaxchiefsworkers" />
		<task name="ajaxwokerschiefs" default="1" label="ajaxwokerschiefs" />
		<task name="getgroupworkers" default="1" label="getgroupworkers" />
		<task name="getorgunit" default="1" label="getorgunit" />
		<task name="staffschedule" default="1" label="staffschedule" />
		<task name="slfstaff" default="1" label="slfstaff" />
		<task name="console" default="1" label="console" />
		<task name="reloadweeksum" default="1" label="reloadweeksum" />
	</allowTasks>
</config>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/transfer/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/component.config.dtd">
<config>
    <defaultTask value="add" />
    <tasks>
        <task name="add" default="1" label="add" />
        <task name="edit" default="1" label="edit" />
        <task name="approve" default="1" label="approve" />
        <task name="approvedone" default="1" label="approvedone" />
        <task name="delete" default="1" label="delete" />
    </tasks>
    <allowTasks>
        <task name="next" default="1" label="next" />
        <task name="cancel" default="1" label="cancel" />
        <task name="save" default="1" label="save" />
    </allowTasks>
</config>
