=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/defines/xml/edit.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/edit.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE install SYSTEM "edit.dtd">

    <install>
    ...
    </install>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT install (params)*>
<!ATTLIST install
    type CDATA #IMPLIED
    version CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT params (param|filter)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT param (option)*>
<!ATTLIST param
    name CDATA #IMPLIED
    type CDATA #IMPLIED
    default CDATA #IMPLIED
    label CDATA #IMPLIED
    must CDATA #IMPLIED
    geokbd CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT filter EMPTY>
<!ATTLIST filter
    name CDATA #IMPLIED
    type CDATA #IMPLIED
    default CDATA #IMPLIED
    label CDATA #IMPLIED
    key_field CDATA #IMPLIED
    value_field CDATA #IMPLIED
    query CDATA #IMPLIED
    select_label CDATA #IMPLIED
    must CDATA #IMPLIED
  >

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/hrgraph/tmpl/copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://apps.magticom.ge/pda/defines/xml/edit.dtd">
<install type="component" version="1.5.0">
	<params>
		<group>
			<param name="START_DATE" type="calendar" default="" label="START_DATE_INC" must="1" />
			<param name="END_DATE" type="calendar" default="" label="END_DATE_INC" must="1" />
		</group>
		<group>
			<param name="COPY_START_DATE" type="calendar" default="" label="COPY_START_DATE" must="1" />
			<param name="COPY_ITERATION" type="list" default="1">
				<option value="1">1 times</option>
				<option value="2">2 times</option>
				<option value="3">3 times</option>
				<option value="4">4 times</option>
				<option value="5">5 times</option>
				<option value="6">6 times</option>
				<option value="7">7 times</option>
				<option value="8">8 times</option>
				<option value="9">9 times</option>
				<option value="10">10 times</option>
			</param>
		</group>
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/newgraphtime/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/edit.dtd">
<install type="component" version="1.5.0">
	<params>
		<param name="LIB_TITLE" type="text" default="" label="Title" must="1" geokbd="1" />
		<param name="LIB_DESC" type="text" default="" label="Description" geokbd="1" />
		<param name="ORG" type="myorg" default="" label="ORG"  must="1" />
		<param name="GROUPS" type="mygroupsrel" default="" label="GROUPS" must="1" />
		<param name="ACTIVE" type="radio" default="1">
			<option value="1">Active Status</option>
			<option value="0">Inactive</option>
		</param>
		<param name="ID" type="hidden" default="" />
	</params>
	<params group="details">
		<param name="START_TIME" type="time" default="" label="Max_START_TIME" must="1" />
		<param name="MIN_WORKING_HOUR" type="number" default="" label="MIN_WORKING_HOUR" must="1"/>
		<param name="MAX_WORKING_HOUR" type="number" default="" label="MAX_WORKING_HOUR" must="1"/>
		<!--		<param name="END_TIME" type="time" default="" label="END_TIME" must="1" />-->
		<!--		<param name="START_BREAK" type="time" default="" label="START_BREAK" />
		<param name="END_BREAK" type="time" default="" label="END_BREAK" />-->
		<param name="REST_MINUTES" type="number" default="" label="REST_MINUTES" must="1"/>
		<param name="HOLIDAY_YN" type="radio" default="" must="1">
			<option value="1">Yes</option>
			<option value="0">No</option>
		</param>
		<param name="COLOR" type="color" default="#990000" label="COLOR" />
		<param name="VACATION_INDEX" type="number" default="1" label="VACATION_INDEX" must="1" step="0.5" />
		<param name="TIME_CODE" type="text" default="" label="code" />
	</params>
</install>
