=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/defines/xml/grid.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/grid.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE install SYSTEM "grid.dtd">

    <install>
    ...
    </install>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT install (filters|params)*>
<!ATTLIST install
    type CDATA #IMPLIED
    version CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT filters (filter)*>
<!ATTLIST filters
    class CDATA #IMPLIED
    type CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT filter EMPTY>
<!ATTLIST filter
    name CDATA #IMPLIED
    type CDATA #IMPLIED
    default CDATA #IMPLIED
    label CDATA #IMPLIED
    class CDATA #IMPLIED
    submit_label CDATA #IMPLIED
    reset_label CDATA #IMPLIED
    show_reset CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT params (param)*>
<!ATTLIST params
    class CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT param EMPTY>
<!ATTLIST param
    order CDATA #IMPLIED
    type CDATA #IMPLIED
    default CDATA #IMPLIED
    label CDATA #IMPLIED
    rclass CDATA #IMPLIED
    key CDATA #IMPLIED
    length CDATA #IMPLIED
    limit_type CDATA #IMPLIED
  >

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/overtimealertworkers/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="page_filter_block" type="h">
		<filter name="firstname" type="stext" default="" label="firstname" class="kbd" />
		<filter name="lastname" type="stext" default="" label="lastname" class="kbd" />
		<filter name="start_date" type="calendar" default="" label="start date" />
		<filter name="end_date" type="calendar" default="" label="end date" />
		<filter name="year" type="year" default="" label="year" />
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="" type="checkall" default="" label="" rclass="text-center"   />
		<param order="worker" type="editlink" label="worker" key="WORKER" rclass="text-left" />
		<param order="t.start_date" type="print" label="Date" key="START_DATE" rclass="text-center" />
		<param order="t.day_count" type="print" label="OVERTIME_HOURS" key="DAY_COUNT" rclass="text-center" />
		<param order="t.info" type="print" label="INFO" key="INFO" rclass="text-left" />
		<param order="approver" type="print" label="APPROVER" rclass="text-center" key="APPROVER" />
		<param order="t.approve_date" type="print" label="APPROVE_DATE" rclass="text-center" key="APPROVE_DATE" />
		<param order="t.status" type="approve" label="status" rclass="text-center" state_id='ID' state_key="STATUS" />
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/r_login_log/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Edited by Irakli Gzirishvili 21-10-2021-->
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="page_filter_block" type="h">
		<filter name="log_ip" type="stext" default="" label="IP" class="kbd" />
		<filter name="browser_name" type="stext" default="" label="BROWSER" class="kbd" />
		<filter name="os_name" type="stext" default="" label="OS NAME" class="kbd" />
		<filter name="log_prev_user_name" type="stext" default="" label="PREV USERNAME" class="kbd" />
		<filter name="log_user_name" type="stext" default="" label="USERNAME" class="kbd" />
		<filter name="start_date" type="calendar" default="" label="start date" />
		<filter name="end_date" type="calendar" default="" label="end date" />
		<filter name="login_ident" type="state" default="-1" label="LOGIN" class="kbd">
			<option value="-1">Select State</option>
			<option value="1">PRIVATE</option>
			<option value="0">OTHER USER</option>
		</filter>	
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>

	<params class="table table-bordered table-condensed table-hover table-striped exporttable" id="exportable">
		<param order=""   type="number" default="" label="#" rclass="text-center" hclass="text-center"/>
		<param order="w.log_ip" type="print" label="IP" key="LOG_IP" rclass="text-center" />
		<param order="w.browser_name" type="print" label="BROWSER" key="BROWSER_NAME" rclass="text-center" />
		<param order="w.os_name" type="print" label="OS NAME" key="OS_NAME" rclass="text-center" />
		<param order="w.log_prev_user_name" type="print" label="PREV USERNAME" key="LOG_PREV_USER_NAME" rclass="text-center" />
		<param order="w.log_user_name" type="print" label="USERNAME" key="LOG_USER_NAME" rclass="text-center" />
		<param order="w.log_date" type="print" label="DATE" key="LOG_DATE" rclass="text-center" />
	</params>

</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/r_sms_service/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="wfirstname" type="printm" label="worker" key="WFIRSTNAME, WLASTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="log_date" type="print" label="LOGING_DATE" key="LOGING_DATE" rclass="text-left" />
		<param order="LOG_FROM" type="print" label="LOG_PHONE" key="LOG_PHONE" rclass="text-left" />
		<param order="" type="print" label="LOG_MSG" key="LOG_TEXT" rclass="text-left" length="3" limit_type="1" />
		<param order="" type="print" label="LOG_RESULT" key="LOG_RESPONSE" rclass="text-left"  length="3" limit_type="1" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/holidayregasusers/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="page_filter_block" type="h">
		<filter name="firstname" type="stext" default="" label="firstname" class="kbd" />
		<filter name="lastname" type="stext" default="" label="lastname" class="kbd" />
		<filter name="org" type="org" default="" label="org" />
		<filter name="start_date" type="calendar" default="" label="start date" />
		<filter name="end_date" type="calendar" default="" label="end date" />
		<!--<filter name="year" type="year" default="" label="year" />-->
		<filter name="hperiod" type="hperiod" default="now" label="hperiod"/>
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="" type="checkall" default="" label="" rclass="text-center"   />
		<param order="worker" type="editlink" label="worker" key="WORKER" rclass="text-left" />
		<param order="t.org" type="org" label="org" rclass="text-center" key="ORG"  />
		
		<param order="htitle" type="print" label="HOLIDAY INFORMATION" key="HTITLE" rclass="text-left" />
		<param order="htype" type="htype" label="HTYPE" key="HTYPE" rclass="text-left" />
		
		<param order="t.start_date" type="print" label="Holiday Start G" key="START_DATE" rclass="text-center" />
		<param order="t.end_date" type="print" label="Holiday End G" key="END_DATE" rclass="text-center" />
		<param order="t.day_count" type="print" label="DAY COUNT G" rclass="text-center" key="DAY_COUNT" />
		<param order="approver" type="print" label="APPROVER" rclass="text-center" key="APPROVER" />
		<param order="t.approve_date" type="print" label="APPROVE_DATE" rclass="text-center" key="APPROVE_DATE" />
		<param order="t.rec_date" type="print" label="REC_DATE" rclass="text-center" key="REC_DATE" />
		<param order="t.w_holiday_comment" type="print" label="comment" key="W_HOLIDAY_COMMENT" rclass="text-center" />
		<param order="t.status" type="approve" label="status" rclass="text-center" state_id='ID' state_key="STATUS" />
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/r_comments/tmpl/export.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://apps.magticom.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<params name="r_comments">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="" type="print" key="EVENT_DATE" default="" label="DATE" rclass="text-left" />
		<param order="" type="editlink" key="WFIRSTNAME, WLASTNAME" default="" label="FIRSTNAME_LASTNAME" rclass="text-left" />
		<param order="" type="print" label="ORG" rclass="text-left" key="ORG_NAME" />
		<param order="" type="print" key="STAFF_SCHEDULE" default="" label="ORG_PLACE" rclass="text-left" />
		<param order="" type="print" label="ACTION" rclass="text-left" key="EVENT_NAME" />
		<param order="" type="print" label="TIME" rclass="text-left" key="EVENT_TIME" />
		<param order="" type="print" label="DELAY_MINUTES" rclass="text-left" key="TIME_MIN" />
		<param order="" type="print" label="USER COMMENT/REASON" rclass="text-left" key="U_COMMENT" />
		<param order="" type="print" label="DICISION_OF_CHIEF" rclass="text-left" key="DICISION_OF_CHIEF" />
		<param order="" type="print" label="CHIEF" rclass="text-left" key="CHIEF" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/pmissionsasworkers/tmpl/export_info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://apps.magticom.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<params name="pmissionsasworkers">
		<param order="" type="number" default="" label="#" rclass="text-center" hclass="text-center"/>
		<param order="" type="editlink" label="worker" key="WFIRSTNAME, WLASTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="" type="print" label="PRIVATE_NUMBER" key="PRIVATE_NUMBER" rclass="text-left" />
		<param order="" type="org" label="org" key="ORG" rclass="text-left" T="1"/>
		<param order="" type="workerUnits" label="org_place" key="WORKER_ID" rclass="text-left" T="1"/>
		<param order="" type="print" label="PTime Start" key="START_DATE" rclass="text-center" />
		<param order="" type="print" label="PTime End" key="END_DATE" rclass="text-center" />
		<param order="" type="printm" label="APPROVER" rclass="text-center" key="AFIRSTNAME, ALASTNAME" T="1" Tscope="person" />
		<param order="" type="print" label="APPROVE_DATE" rclass="text-center" key="APPROVE_DATE" />
		<param order="" type="print" label="UCOMMENT" rclass="text-left" key="UCOMMENT" />
		<param order="" type="print" label="officialtype" rclass="text-left" key="INFO" T="1"/>
		<param order="" type="print" label="REC_DATE" key="REC_DATE" rclass="text-left" />
		<param order="" type="wworker" label="AUTHOR" key="REC_USER" rclass="text-left" T="1"/>
		<param order="" type="approve" label="status" rclass="text-center" state_id='ID' state_key="STATUS" />
		<param order="" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/orgunits/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="page_filter_block" type="h">
		<!--<filter name="org" type="org" default="" label="org" class="kbd" />-->
<!--		<filter name="lastname" type="text" default="" label="lastname" class="kbd" />
		<filter name="position" type="text" default="" label="position" class="kbd"  />-->
		<!--<filter name="department" type="department" default="" label="department" />-->
		<!--<filter name="chapter" type="chapter" default="" label="chapter" />-->
		<!--<filter name="user_role" type="userrole" default="" label="User_Role" />-->
		<!--<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />-->
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="workername" type="workers" label="worker" key="WORKERNAME" id='ID' rclass="text-left" />
		<param order="u.position" type="print" label="position" key="POSITION" rclass="text-left" />
		<param order="u.org_place" type="print" label="org_place" key="ORG_PLACE" rclass="text-center" />
		<param order="u.user_type" type="usertype" label="user_type" key="USER_TYPE" rclass="text-center" />
		<param order="u.id" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/wmissionsasworkers/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="page_filter_block" type="h">
		<filter name="firstname" type="stext" default="" label="firstname" class="kbd" />
		<filter name="lastname" type="stext" default="" label="lastname" class="kbd" />
		<filter name="private_number" type="stext" default="" label="private_number" class="kbd" />
		<filter name="org" type="org" default="" label="org" />
		<filter name="org_place" type="unit" default="" label="unit" />
		<filter name="start_date" type="calendar" default="" label="start date" />
		<filter name="end_date" type="calendar" default="" label="end date" />
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" hclass="text-center"/>
		<param order="" type="checkall" default="" label="" rclass="text-center"   />
		<param order="wfirstname" type="editlink" label="worker" key="WFIRSTNAME, WLASTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="app.private_number" type="print" label="PRIVATE_NUMBER" key="PRIVATE_NUMBER" rclass="text-left" />
		<param order="t.org" type="org" label="org" key="ORG" rclass="text-left" T="1"/>
		<param order="t.status" type="approve" labels="status" rclass="text-center" state_id='ID' state_key="STATUS" hclass="text-center"/>
		<param order="" type="workerUnits" label="org_place" key="WORKER_ID" rclass="text-left" />
		<param order="t.files" type="fileprint" label="files" key="FILES" rclass="text-left" />
		<param order="t.start_date" type="print" label="Holiday Start G" key="START_DATE" rclass="text-center" />
		<param order="t.end_date" type="print" label="Holiday End G" key="END_DATE" rclass="text-center" />
		<param order="t.day_count" type="print" label="DAY COUNT G" key="DAY_COUNT" rclass="text-center" />
		<param order="afirstname" type="printm" label="APPROVER" rclass="text-center" key="AFIRSTNAME, ALASTNAME" T="1" Tscope="person" />
		<param order="t.approve_date" type="print" label="APPROVE_DATE" rclass="text-center" key="APPROVE_DATE" />
		<param order="t.rec_date" type="print" label="REC_DATE" key="REC_DATE" rclass="text-left" />
		<param order="t.ucomment" type="print" label="INFO" key="UCOMMENT" rclass="text-left" T="1"/>
		<param order="t.rec_user" type="wworker" label="AUTHOR" key="REC_USER" rclass="text-left" T="1"/>
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" hclass="text-center"/>
	</params>
</install>
