=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/defines/xml/grid.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/grid.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE install SYSTEM "grid.dtd">

    <install>
    ...
    </install>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT install (filters|params)*>
<!ATTLIST install
    type CDATA #IMPLIED
    version CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT filters (filter)*>
<!ATTLIST filters
    class CDATA #IMPLIED
    type CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT filter EMPTY>
<!ATTLIST filter
    name CDATA #IMPLIED
    type CDATA #IMPLIED
    default CDATA #IMPLIED
    label CDATA #IMPLIED
    class CDATA #IMPLIED
    submit_label CDATA #IMPLIED
    reset_label CDATA #IMPLIED
    show_reset CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT params (param)*>
<!ATTLIST params
    class CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT param EMPTY>
<!ATTLIST param
    order CDATA #IMPLIED
    type CDATA #IMPLIED
    default CDATA #IMPLIED
    label CDATA #IMPLIED
    rclass CDATA #IMPLIED
    key CDATA #IMPLIED
    length CDATA #IMPLIED
    limit_type CDATA #IMPLIED
  >

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/f_benefits/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="page_filter_block" type="h">
		<filter name="lib_title" type="stext" default="" label="name" class="kbd" />
		<filter name="accounting_code" type="stext" default="" label="ACCOUNTING_CODE" class="kbd" />
		<filter name="active" type="state" default="-1" label="State">
			<option value="-1">Select State</option>
			<option value="0">Inactive</option>
			<option value="1">Active Status</option>
		</filter>
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" hclass="text-center" />
		<param order="" type="checkall" default="" label="" rclass="text-center"   />
		<param order="t.lib_title" type="editlink" label="Title" key="LIB_TITLE" rclass="text-left" T="1"/>
		<param order="t.lib_desc" type="print" label="Description" key="LIB_DESC" rclass="text-left" />
		<param order="t.accounting_code" type="print" label="ACCOUNTING_CODE" key="ACCOUNTING_CODE" rclass="text-left" />
		<param order="t.fields" type="fields" label="fields" rclass="text-center" key="FIELDS" />
		<param order="t.active" type="state" label="State" rclass="text-center" state_id='ID' state_key="ACTIVE" />
		<param order="t.ordering" type="print" label="ordering" key="ORDERING" rclass="text-center" />
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" hclass="text-center"/>
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/r_cwr/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://apps.magticom.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="table table-bordered table-condensed table-filter-vertical" type="v">
		<filter name="worker" type="chiefworkers" default="" label="worker" class="kbd"  />
		<!--<filter name="lastname" type="stext" default="" label="lastname" class="kbd"  />-->
		<!--<filter name="cat_id" type="category" default="1" label="category"  />-->
		<!--<filter name="sphere" type="sphere" default="" label="sphere" />-->
		<!--<filter name="department" type="department" default="" label="department" />-->
		<!--<filter name="chapter" type="chapter" default="" label="chapter" />-->
		<filter name="start_date" type="calendar" default="now -1 day" label="Start Date" />
		<filter name="end_date" type="calendar" default="now +1 day" label="End Date" />
		<filter name="org" type="org" default="" label="org" />
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="" type="checkall" default="" label="" rclass="text-center"   />
		<param order="wfirstname" type="editlink" label="worker" key="WFIRSTNAME, WLASTNAME, ORG_NAME" Tscope="person" />
		<param order="w.section_id" type="print" label="Section" rclass="text-left" key="SECTION" />
		<param order="t.start_date" type="print" label="visitorsReport Start G" key="START_DATE" rclass="text-center" />
		<param order="t.end_date" type="print" label="visitorsReport End G" key="END_DATE" rclass="text-center" />
		<param order="t.day_count" type="print" label="DAY COUNT G" rclass="text-center" key="DAY_COUNT" />
		<param order="approver" type="print" label="Author" rclass="text-center" key="APPROVER" />
		<param order="t.rec_date" type="print" label="BULLETIN_REC_DATE" rclass="text-center" key="REC_DATE" />
		<param order="t.status" type="bulletintype" label="status" rclass="text-center" state_id='ID' state_key="STATUS" />
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/overtimes/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="" type="checkall" default="" label="" rclass="text-center"   />
		<param order="wfirstname" type="editlink" label="worker" key="WFIRSTNAME, WLASTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="t.org" type="org" label="ORG" key="ORG" rclass="text-left" T="1"/>
		<param order="ww.staff_schedule" type="staffschedule" label="staff_schedule" key="STAFF_SCHEDULE" rclass="text-left" T="1"/>
		<param order="ww.org_place_name" type="print" label="org_place" key="ORG_PLACE_NAME" rclass="text-left" T="1"/>
		<param order="t.status" type="approve" label="status" rclass="text-center" state_id='ID' state_key="STATUS" />
		<param order="t.start_date" type="print" label="Date" key="START_DATE" rclass="text-center" />
		<param order="t.day_count" type="timeprint" dec="2" label="OVERTIME_HOURS" key="DAY_COUNT" rclass="text-center" />
		<param order="t.info" type="print" label="INFO" key="INFO" rclass="text-left" />
		<param order="afirstname" type="printm" label="APPROVER" rclass="text-center" key="AFIRSTNAME, ALASTNAME" T="1" Tscope="person" />
		<param order="t.approve_date" type="print" label="APPROVE_DATE" rclass="text-center" key="APPROVE_DATE" />
		<param order="t.rec_date" type="print" label="REC_DATE" key="REC_DATE" rclass="text-left" />
		<param order="t.rec_user" type="wworker" label="AUTHOR" key="REC_USER" rclass="text-left" T="1"/>
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/mytasks/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="page_filter_block" type="h">
		<filter name="firstname" type="stext" default="" label="worker" class="kbd" />
		<!--<filter name="lastname" type="stext" default="" label="lastname" class="kbd" />-->
		<filter name="org" type="org" default="0" label="org" />
		<filter name="lib_title" type="stext" default="" label="HTYPE" class="kbd" />
		<filter name="start_date" type="calendar" default="" label="start date" />
		<filter name="end_date" type="calendar" default="" label="end date" />
		<filter name="tasktitle" type="stext" default="" label="task_title"/>
		<filter name="wstate" type="state" default="-1" label="State">
			<option value="-1">Select State</option>
			<option value="0">T_CONFIRMATION</option>
			<option value="1">T_CONFIRMED</option>
			<option value="2">T_DECLINED</option>
		</filter>
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" hclass="text-center" />
		<param order="" type="checkall" default="" label="" rclass="text-center" key="TASK_ID"  />
		<param order="FIRSTNAME" type="joinprint"  patern="FIRSTNAME LASTNAME" label="worker" key="WORKER" rclass="text-left" T="1" Tscope="person" />
		<param order="org" type="org" label="org" key="ORG" rclass="text-left" T="1"/>
		<param order="lib_title" type="print" label="HTYPE" key="LIB_TITLE" rclass="td_left" read_key="LOG" T="1"/>
		<param order="t.start_date" type="print" label="Holiday Start" key="START_DATE" rclass="text-center" />
		<param order="t.end_date" type="print" label="Holiday End" key="END_DATE" rclass="text-center" />
		<param order="t.day_count" type="print" label="DAY COUNT" rclass="text-center" key="DAY_COUNT" />
		<param order="t.replacing_workers" type="fpersons" label="replacing_workers" rclass="text-left" key="REPLACING_WORKERS" T="1" Tscope="person" />
		<param order="t.task_title" type="print" label="TASK_TITLE" key="TASK_TITLE"  link_key="TASK_ID"  read_key="LOG" rclass="td_left" T="1"/>
		<param order="t.task_create_date" type="print" label="Create Date" key="WCREATE_DATE" rclass="td_centered"   read_key="LOG"  />
		<param order="t.task_due_date" type="print" label="TASK_DUE_DATE" key="DUE_DATE" rclass="td_centered"   read_key="LOG"  late_key="LATENESS"   />
		<param order="t.state" type="approvestate" label="State" rclass="text-center" state_key="STATE" />
		<param order="t.task_id" type="print" label="ID" key="TASK_ID" rclass="text-center" hclass="text-center"  read_key="LOG"   />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/overtimeworkers/tmpl/export.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://apps.magticom.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<params name="overtimeworkers">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="" type="printm" label="worker" key="WFIRSTNAME, WLASTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="" type="print" label="ORG" key="ORG_NAME" rclass="text-left" T="1"/>
		<param order="" type="staffschedule" label="staff_schedule" key="STAFF_SCHEDULE" rclass="text-left" T="1"/>
		<param order="" type="print" label="org_place" key="ORG_PLACE_NAME" rclass="text-left" T="1"/>
		<param order="" type="print" label="Date" key="START_DATE" rclass="text-center" />
		<param order="" type="numberprint" dec="2" label="OVERTIME_HOURS" key="DAY_COUNT" rclass="text-center" />
		<param order="" type="print" label="INFO" key="INFO" rclass="text-left" />
		<param order="" type="print" label="APPROVER" rclass="text-center" key="APPROVER" T="1"/>
		<param order="" type="print" label="APPROVE_DATE" rclass="text-center" key="APPROVE_DATE" />
		<param order="" type="print" label="REC_DATE" key="REC_DATE" rclass="text-left" />
		<param order="" type="wworker" label="AUTHOR" key="REC_USER" rclass="text-left" T="1"/>
		<param order="" type="approve" label="status" rclass="text-center" state_id='ID' state_key="STATUS" />
		<param order="" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/cws/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="page_filter_block" type="h">
		<filter name="firstname" type="stext" default="" label="firstname" class="kbd" />
		<filter name="lastname" type="stext" default="" label="lastname" class="kbd" />
		<filter name="org" type="myorg" default="" label="org" />
		<filter name="position" type="stext" default="" label="position" class="kbd" />
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="wfirstname," type="printm" label="name, surname" key="WFIRSTNAME, WLASTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="" type="orgorg" label="ORG" key="ORG.ORG" rclass="text-left"  T="1"/>
		<param order="" type="staffschedule" multy="1" label="STAFF_SCHEDULE" rclass="text-left" key="ORG.STAFF_SCHEDULE" T="1"/>
		<param order="" type="position" multy="1" label="POSITION" rclass="text-left" key="ORG.POSITION" T="1"/>
		<param order="email" type="print" default="" rclass="text-left"  label="EMAIL"  key="EMAIL" />
		<param order="mobile_phone_number" type="print" default="" rclass="text-left"  label="MOBILE_PHONE_NUMBER"  key="MOBILE_PHONE_NUMBER" />
		<param order="" type="print" multy="1" default="" rclass="text-left"  label="CONTRACTS_DATE"  key="ORG.CONTRACTS_DATE" />
		<param order="" type="print" multy="1" default="" rclass="text-left"  label="CONTRACT_END_DATE"  key="ORG.CONTRACT_END_DATE" />
		<!--<param order="" type="wholiday" label="WAGE HOLIDAY COUNT" key="ID" rclass="text-center" />-->
		<!--<param order="" type="wlholiday" label="WAGELESS HOLIDAY COUNT" key="ID" rclass="text-center" />-->
		<!--<param order="contract_end_date" type="print" default="" rclass="text-left"  label="CONTRACT_END_DATE"  key="S_CONTRACT_END_DATE" />-->
		<!--<param order="" type="tooltip" label="CHIEFS" key="ALL_CHIEFS" rclass="text-left" length="2" />-->
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/menus/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="page_filter_block" type="h">
		<filter name="lib_title" type="text" default="" label="title" geokbd="1" />
		<filter name="lib_option" type="text" default="" label="lib_option" />
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" hclass="text-center"/>
		<param order="" type="checkall" default="" label="" rclass="text-center"   />
		<param order="" type="editlink" label="Title" key="LIB_TITLE" rclass="text-left" />
		<param order="" type="print" label="LIB_OPTION" key="LIB_OPTION" rclass="text-center" />
		<param order="" type="state" label="State" rclass="text-center" state_id='ID' state_key="ACTIVE" hclass="text-center"/>
		<param order="" type="print" label="ORDERING" key="ORDERING" rclass="text-center" hclass="text-center"/>
		<param order="" type="print" label="ID" key="ID" rclass="text-center" hclass="text-center"/>
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/r_comments/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="table table-bordered table-condensed table-filter-vertical" type="v">
		<filter name="firstname" type="stext" default="" label="firstname" class="kbd"  />
		<filter name="lastname" type="stext" default="" label="lastname" class="kbd"  />
		<!--<filter name="category_id" type="category" default="" label="category"  />-->
		<filter name="start_date" type="calendar" default="now -7 day" label="Start Date" />
		<filter name="end_date" type="calendar" default="now + 1 day" label="End Date" />
		<filter name="orgid" type="org" default="" label="org" />
		<filter name="org_place" type="unit" default="" label="unit"  elementid="orgid" />
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" />
<!--		<param order="" type="checkall" default="" label="" rclass="text-center"   />-->
		<param order="t.event_date" type="print" label="DATE" key="EVENT_DATE" rclass="text-center" />
		<param order="wfirstname" type="editlink" label="FIRSTNAME_LASTNAME" key="WFIRSTNAME, WLASTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="" type="print" label="ORG" rclass="text-left" key="ORG_NAME" />

		<param order="" type="print" label="ORG_PLACE" rclass="text-left" key="STAFF_SCHEDULE" />
		<param order="" type="print" label="ACTION" rclass="text-left" key="EVENT_NAME" />
		<param order="" type="print" label="TIME" rclass="text-left" key="EVENT_TIME" />
		<param order="" type="print" label="DELAY_MINUTES" rclass="text-left" key="TIME_MIN" />
		<param order="" type="print" label="USER COMMENT/REASON" rclass="text-left" key="U_COMMENT" />
		<param order="" type="print" label="DICISION_OF_CHIEF" rclass="text-left" key="DICISION_OF_CHIEF" />
		<param order="" type="print" label="CHIEF" rclass="text-left" key="CHIEF" />
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" />

	</params>
</install>
