=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/defines/xml/grid.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/grid.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE install SYSTEM "grid.dtd">

    <install>
    ...
    </install>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT install (filters|params)*>
<!ATTLIST install
    type CDATA #IMPLIED
    version CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT filters (filter)*>
<!ATTLIST filters
    class CDATA #IMPLIED
    type CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT filter EMPTY>
<!ATTLIST filter
    name CDATA #IMPLIED
    type CDATA #IMPLIED
    default CDATA #IMPLIED
    label CDATA #IMPLIED
    class CDATA #IMPLIED
    submit_label CDATA #IMPLIED
    reset_label CDATA #IMPLIED
    show_reset CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT params (param)*>
<!ATTLIST params
    class CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT param EMPTY>
<!ATTLIST param
    order CDATA #IMPLIED
    type CDATA #IMPLIED
    default CDATA #IMPLIED
    label CDATA #IMPLIED
    rclass CDATA #IMPLIED
    key CDATA #IMPLIED
    length CDATA #IMPLIED
    limit_type CDATA #IMPLIED
  >

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/r_outs/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="table table-bordered table-condensed table-filter-vertical" type="v">
		<filter name="firstname" type="stext" default="" label="firstname" class="kbd"  />
		<filter name="lastname" type="stext" default="" label="lastname" class="kbd"  />
		<filter name="start_date" type="calendar" default="now - 7 days" label="Start Date" />
		<filter name="end_date" type="calendar" default="now" label="End Date" />
		<filter name="cat_id" type="category" default="-1" label="category"  />
		<filter name="org" type="org" default="" label="org" />
		<filter name="org_place" type="unit" default="" label="unit" />
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>

</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/r_lateness/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="table table-bordered table-condensed table-filter-vertical" type="v">
		<filter name="firstname" type="stext" default="" label="firstname" class="kbd"  />
		<filter name="lastname" type="stext" default="" label="lastname" class="kbd"  />
		<filter name="private_number" type="stext" default="" label="private_number" class="kbd"  />
		<filter name="staff_schedule" type="stext" default="" label="staff_schedule" class="kbd"  />
		<filter name="position" type="stext" default="" label="position" class="kbd"  />
		<filter name="org" type="org" default="" label="org" />
		<filter name="org_place" type="unit" default="" label="unit"  elementid="org" />
		<filter name="start_date" type="calendar" default="now" label="Start Date" />
		<filter name="end_date" type="calendar" default="now" label="End Date" />
		<filter name="cat_id" type="category" default="-1" label="category"  />
<!--		<filter name="c_resolution" type="state" default="0" label="status">
			<option value="-1">select category</option>
			<option value="0">PENDING</option>
			<option value="1">ACCEPTED</option>
			<option value="2">DECLINED</option>
		</filter>-->
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>

</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/bulletins/tmpl/export.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<params name="Bulletins">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="wfirstname" type="editlink" label="worker" key="WFIRSTNAME, WLASTNAME" rclass="text-left" T="1" Tscope="person"/>
		<param order="app.private_number" type="print" label="PRIVATE_NUMBER" key="PRIVATE_NUMBER" rclass="text-left" />
		<param order="" type="task" label="Actions" rclass="text-center" default="1"  key="ID">
			<option value="confirm">confirm</option>
		</param>
		<param order="t.org" type="org" label="org" rclass="text-center" key="ORG"  T="1"/>
		<param order="" type="workerUnits" label="org_place" key="WORKER_ID" rclass="text-left" />
		<param order="t.day_count" type="print" label="DAY COUNT G" rclass="text-center" key="DAY_COUNT" />
		<param order="t.ucomment" type="print" label="UComment" rclass="text-left" key="UCOMMENT" limit="3" />
		<param order="w.mobile_phone_number" type="print" label="mobile_phone_number" rclass="text-center" key="MOBILE_PHONE_NUMBER" />
		<param order="t.start_date" type="print" label="Bulletins Start G" key="START_DATE" rclass="text-center" />
		<param order="t.end_date" type="print" label="Bulletins End G" key="END_DATE" rclass="text-center" />
		<param order="approver" type="wworker" label="approver" rclass="text-center" key="APPROVE" T="1" />
		<param order="t.approve_date" type="print" label="APPROVE_DATE" key="APPROVE_DATE" rclass="text-left" />
		<param order="t.additional_status" type="switch" label="additional_status" rclass="text-center" key="ADDITIONAL_STATUS" >
			<option value="1">yes</option>
			<option value="0"></option>
		</param>
		<param order="t.files" type="fileprint" label="files" key="FILES" rclass="text-left" />
		<param order="t.rec_date" type="print" label="REC_DATE" key="REC_DATE" rclass="text-left" />
		<param order="t.rec_user" type="wworker" label="AUTHOR" key="REC_USER" rclass="text-left"T="1" />
		<param order="t.status" type="bulletintype" label="status" rclass="text-center" state_id='ID' state_key="STATUS" />
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/r_active_sessions_log/tmpl/export.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Edited by Irakli Gzirishvili 21-10-2021.-->
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<params name="Workers">
		<param order=""   type="number" default="" label="#" rclass="text-center" hclass="text-center"/>
		<param order="" type="checkall" default="" label="" rclass="text-center"  hclass="text-center" />
		<param order="" type="stringdate" label="SESSION START" key="LOG_DATE" rclass="text-right" />
		<param order="" type="editlink" label="worker" key="WFIRSTNAME, WLASTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="" type="print" label="ORG" key="ORG_NAME" rclass="text-left" />
		<param order="" type="print" label="POSITION" key="POSITION" rclass="text-left" />
		<param order="" type="print" label="IP" key="LOG_IP" rclass="text-center" />
		<param order="" type="print" label="BROWSER" key="BROWSER_NAME" rclass="text-center" />
		<param order="" type="print" label="OS NAME" key="OS_NAME" rclass="text-center" />
		<param order="" type="print" label="START DATE" key="START_DATE" rclass="text-center" />
		<param order="" type="print" label="END DATE" key="END_DATE" rclass="text-center" />
		<param order="" type="print" label="UPDATE DATE" key="LOG_DATE" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/person_orgs/tmpl/export.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<params class="table table-bordered table-condensed table-hover table-striped exporttable" id="exportable" name="workers" >
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="pr.firstname" type="print" label="FIRSTNAME" key="FIRSTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="pr.lastname" type="print" label="LASTNAME" key="LASTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="t.org" type="org" label="ORG" key="ORG" rclass="text-left"  T="1"/>
		<param order="" type="mainunit" label="MAINUNIT" key="ORG_PLACE" tipkey="MAINUNIT" rclass="text-left"  T="1"/>
		<param order="un.lib_title" type="print" label="STRUCTURE" key="ORG_PLACE_NAME" rclass="text-left"  T="1"/>
		<param order="t.staff_schedule" type="staffschedule" label="staffschedule" key="STAFF_SCHEDULE" rclass="text-left" T="1"/>
		<param order="lss.position" type="position" label="position" key="POSITION" rclass="text-left" T="1"/>
		<param order="t.contract_type" type="switch" label="CONTRACT_TYPE" key="CONTRACT_TYPE" rclass="text-left">
			<option value="1">Standard Contract</option>
		</param>
		<param order="t.contracts_date" type="date" format="%Y-%m-%d" label="CONTRACTS_DATE" key="CONTRACTS_DATE" rclass="text-left"  />
		<param order="t.contract_end_date"  type="date" format="%Y-%m-%d" label="CONTRACT_END_DATE" key="CONTRACT_END_DATE" rclass="text-left"  />
		<!--		<param order="pr.change_date"  type="date" format="%Y-%m-%d" label="ASSIGNMENT_DATE" key="CHANGE_DATE" rclass="text-left"  />-->
		<param order="lss.chief_schedule" type="staffschedule" label="CHIEF_SCHEDULE" rclass="text-center" key="CHIEF_SCHEDULE" T="1"/>
		<param order="assignment_date" type="date" format="%Y-%m-%d" label="ASSIGNMENT_DATE" rclass="text-center" key="ASSIGNMENT_DATE" />
		<param order="t.active" type="wstatus" label="STATUS" rclass="text-center" key="ACTIVE" />
		<param order="t.release_files" type="fileprint" label="RELEASE_FILES" key="RELEASE_FILES" rclass="text-center" />
		<param order="" type="print" label="changing" rclass="text-center" />
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/pmissions/tmpl/default_info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="" type="checkall" default="" label="" rclass="text-center"   />
		<param order="wfirstname" type="editlink" label="worker" key="WFIRSTNAME, WLASTNAME" rclass="text-left" T="1" Tscope="person" />
		<param order="w.org" type="org" label="org" key="ORG" rclass="text-left" T="1"/>
		<param order="t.status" type="approve" label="status" rclass="text-center" state_id='ID' state_key="STATUS" />
		<param order="t.start_date" type="print" label="PTime Start" key="START_DATE" rclass="text-center" />
		<param order="t.end_date" type="print" label="PTime End" key="END_DATE" rclass="text-center" />
		<param order="afirstname" type="printm" label="APPROVER" rclass="text-center" key="AFIRSTNAME, ALASTNAME" T="1" Tscope="person" />
		<param order="t.approve_date" type="print" label="APPROVE_DATE" rclass="text-center" key="APPROVE_DATE" />
		<param order="" type="print" label="UCOMMENT" rclass="text-left" key="UCOMMENT" />
		<param order="" type="print" label="officialtype" rclass="text-left" key="INFO" T="1"/>
		<param order="t.rec_date" type="print" label="REC_DATE" key="REC_DATE" rclass="text-left" />
		<param order="t.rec_user" type="wworker" label="AUTHOR" key="REC_USER" rclass="text-left" T="1"/>
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/unitorgs/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" hclass="text-center" />
		<param order="" type="checkall" default="" label="" rclass="text-center"   />
		<param order="t.lib_title" type="editlink" label="Title" key="LIB_TITLE" rclass="text-left" T="1"/>
		<param order="t.lib_desc" type="print" label="Description" key="LIB_DESC" rclass="text-left" />
		<param order="t.lib_tin" type="print" label="tin" rclass="text-center" key="LIB_TIN" />
		<param order="t.active" type="state" label="State" rclass="text-center" state_id='ID' state_key="ACTIVE" hclass="text-center"/>
		<param order="t.ordering" type="print" label="ordering" key="ORDERING" rclass="text-center" hclass="text-center"/>
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" hclass="text-center"/>
	</params>
</install>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/components/job_descriptions/tmpl/default.xml
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE install SYSTEM "http://web.magti.ge/pda/defines/xml/grid.dtd">
<install type="component" version="1.5.0">
	<filters class="page_filter_block" type="h">
		<filter name="lib_title" type="stext" default="" label="TEXT_SEARCH" class="kbd" />
		<filter name="active" type="state" default="-1" label="State">
			<option value="-1">Select State</option>
			<option value="0">Inactive</option>
			<option value="1">Active Status</option>
		</filter>
		<filter type="buttons" default="" submit_label="Filter" reset_label="Clear" show_reset= "1" />
	</filters>
	<params class="table table-bordered table-condensed table-hover table-striped">
		<param order="" type="number" default="" label="#" rclass="text-center" />
		<param order="" type="checkall" default="" label="" rclass="text-center"   />
		<param order="t.lib_title" type="editlink" label="Title" key="LIB_TITLE" rclass="text-left" T="1"/>
		<param order="t.lib_goal" type="print" label="LIB_GOAL" key="LIB_GOAL" rclass="text-left" />
		<param order="t.active" type="state" label="State" rclass="text-center" state_id='ID' state_key="ACTIVE" />
		<param order="t.ordering" type="print" label="ordering" key="ORDERING" rclass="text-center" />
		<param order="t.id" type="print" label="ID" key="ID" rclass="text-center" />
	</params>
</install>
