=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/defines/xml/table.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//Kevlishvili//TABLE//EN
    SYSTEM ID: http://web.magti.ge/pda/defines/xml/table.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">

    <table>
    ...
    </table>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT table (column)*>
<!ATTLIST table
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT column EMPTY>
<!ATTLIST column
    comment CDATA #IMPLIED
    default CDATA #IMPLIED
    length CDATA #IMPLIED
    null CDATA #IMPLIED
    type CDATA #IMPLIED
    name CDATA #IMPLIED
  >

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/lib_apis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Created by Irakli Gzirishvili 28-10-2021-->
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="lib_apis" history="yes">
	<columns>
		<column name="id" type="number" null="n" />
		<column name="lib_title" type="varchar2" length="500" Ti="1" />
		<column name="lib_desc" type="varchar2" length="4000" />
		<column name="active" type="number" null="n" default="1 " />
		<column name="ordering" type="number" null="n" default="999" />
		<column name="client_id" type="number" default="00" />

		<column name="apiid" type="varchar2" length="4000" />
		<column name="apikey" type="varchar2" length="4000" />
		<column name="apitime" type="number" default="5" />
		<column name="change_user" type="number" default="00" />
		<column name="change_date"  type="date" />
		
		<column name="api_tables0" type="varchar2" length="4000" />
		<column name="api_tables1" type="varchar2" length="4000" />
		<column name="api_tables2" type="varchar2" length="4000" />
		<column name="api_tables3" type="varchar2" length="4000" />
		<column name="api_tables4" type="varchar2" length="4000" />
		<column name="api_tables5" type="varchar2" length="4000" />
		<column name="api_tables6" type="varchar2" length="4000" />
		<column name="api_tables7" type="varchar2" length="4000" />
		<column name="api_tables8" type="varchar2" length="4000" />
		<column name="api_tables9" type="varchar2" length="4000" />
		<column name="api_tables10" type="varchar2" length="4000" />
	        <column name="modify_user" type="number" />
                <column name="modify_date" type="date" />
     	</columns>
	<sequence  name="sqs_apis" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/lib_user_holiday_limit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://apps.magticom.ge/pda/defines/xml/table.dtd">
<table name="lib_user_holiday_limit" history="yes">
	<columns>
		<column name="id" type="number" null="n" />
		<column name="worker" type="number" null="n" />
		<column name="year" type="number" null="n" />
		<column name="count" type="number" null="n" />
		<column name="htype" type="number" null="n" />
		<column name="aworker" type="number"  default="00" />
		<column name="client_id" type="number" default="00" />
		<column name="start_date" type="date"  />
		<column name="end_date" type="date"  />
		<column name="c_limit" type="number"  />
		<column name="org" type="number"  />
	     <column name="modify_user" type="number" />
          <column name="modify_date" type="date" />
     </columns>
	<history>
		<column name="id" type="number" null="n" />
		<column name="worker" type="number" null="n" />
		<column name="year" type="number" null="n" />
		<column name="count" type="number" null="n" />
		<column name="htype" type="number" null="n" />
		<column name="aworker" type="number"  default="00" />
		<column name="start_date" type="date"  />
		<column name="end_date" type="date"  />
		<column name="c_limit" type="number"  />
	
		<column name="org" type="number"  />
		<column name="client_id" type="number" default="00" />
	     <column name="modify_user" type="number" />
          <column name="modify_date" type="date" />
     </history>
	<sequence  name="sqs_lib_user_holiday_limit" />
	<histsequence  name="sqs_holiday_limit_hist" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/lib_benefits_fines.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="lib_benefits_fines" history="yes">
	<columns>
		<column name="id" type="number" null="n"/>
		<column name="lib_title" type="varchar2" length="500"/>
		<column name="lib_desc" type="varchar2" length="4000"/>
		<column name="files" type="varchar2" length="4000"  />
		<column name="active" type="number" null="n" default="1 "/>
		<column name="ordering" type="number" null="n" default="999"/>
		<column name="client_id" type="number" default="00"/>
		<column name="must" type="number" />
		<column name="worker" type="varchar2" length="500" />
	     <column name="modify_user" type="number" />
          <column name="modify_date" type="date" />
     </columns>
	<history>
		<column name="lib_title" type="varchar2" length="500"/>
		<column name="lib_desc" type="varchar2" length="4000"/>
		<column name="files" type="varchar2" length="4000"  />
		<column name="active" type="number" null="n" default="1 "/>
		<column name="ordering" type="number" null="n" default="999"/>
		<column name="client_id" type="number" default="00"/>
		<column name="must" type="number" />
		<column name="worker" type="varchar2" length="500" />
	     <column name="modify_user" type="number" />
          <column name="modify_date" type="date" />
     </history>
	<sequence name="sqs_benefits_fines"/>
	<histsequence  name="sqs_benefits_fines_hist" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/hrs_table.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://apps.magticom.ge/pda/defines/xml/table.dtd">
<table name="hrs_table" history="yes">
	<columns>
		<column name="id" type="number" null="n" />
		<column name="worker" type="number" null="n" />
		<column name="bill_id" type="number" null="n" />
		<column name="day01" type="number" default="00" />
		<column name="day02" type="number" default="00" />
		<column name="day03" type="number" default="00" />
		<column name="day04" type="number" default="00" />
		<column name="day05" type="number" default="00" />
		<column name="day06" type="number" default="00" />
		<column name="day07" type="number" default="00" />
		<column name="day08" type="number" default="00" />
		<column name="day09" type="number" default="00" />
		<column name="day10" type="number" default="00" />
		<column name="day11" type="number" default="00" />
		<column name="day12" type="number" default="00" />
		<column name="day13" type="number" default="00" />
		<column name="day14" type="number" default="00" />
		<column name="day15" type="number" default="00" />
		<column name="daysum01" type="number" default="00" />
		<column name="day16" type="number" default="00" />
		<column name="day17" type="number" default="00" />
		<column name="day18" type="number" default="00" />
		<column name="day19" type="number" default="00" />
		<column name="day20" type="number" default="00" />
		<column name="day21" type="number" default="00" />
		<column name="day22" type="number" default="00" />
		<column name="day23" type="number" default="00" />
		<column name="day24" type="number" default="00" />
		<column name="day25" type="number" default="00" />
		<column name="day26" type="number" default="00" />
		<column name="day27" type="number" default="00" />
		<column name="day28" type="number" default="00" />
		<column name="day29" type="number" default="00" />
		<column name="day30" type="number" default="00" />
		<column name="day31" type="number" default="00"  />
		<column name="daysum02" type="number"  default="00" />
		<column name="daysum" type="number" default="00" />
		<column name="sumhour" type="number" default="00" />
		<column name="overtimehour" type="number" default="00" />
		<column name="nighthour" type="number" default="00" />
		<column name="holidayhour" type="number" default="00" />
		<column name="otherhour" type="number" default="00" />
		<column name="bulletins" type="number" default="00" />
		<column name="holiday" type="number" default="00" />
		<column name="nholiday" type="number"  default="00"/>
		<column name="other" type="number" default="00" />
		<column name="holidays" type="number" default="00" />	
		<column name="status" type="number" default="00" />
		<column name="change_woker" type="number" default="00" />
		<column name="change_date" type="date" />
		<column name="approve" type="number" default="00"/>
		<column name="approve_date" type="date" />
		<column name="org"  type="number" default="00"/>
		<column name="client_id" type="number" default="00" />
	</columns>
	<history>
		<column name="worker" type="number" null="n" />
		<column name="bill_id" type="number" null="n" />
		<column name="day01" type="number" default="00" />
		<column name="day02" type="number" default="00" />
		<column name="day03" type="number" default="00" />
		<column name="day04" type="number" default="00" />
		<column name="day05" type="number" default="00" />
		<column name="day06" type="number" default="00" />
		<column name="day07" type="number" default="00" />
		<column name="day08" type="number" default="00" />
		<column name="day09" type="number" default="00" />
		<column name="day10" type="number" default="00" />
		<column name="day11" type="number" default="00" />
		<column name="day12" type="number" default="00" />
		<column name="day13" type="number" default="00" />
		<column name="day14" type="number" default="00" />
		<column name="day15" type="number" default="00" />
		<column name="daysum01" type="number" default="00" />
		<column name="day16" type="number" default="00" />
		<column name="day17" type="number" default="00" />
		<column name="day18" type="number" default="00" />
		<column name="day19" type="number" default="00" />
		<column name="day20" type="number" default="00" />
		<column name="day21" type="number" default="00" />
		<column name="day22" type="number" default="00" />
		<column name="day23" type="number" default="00" />
		<column name="day24" type="number" default="00" />
		<column name="day25" type="number" default="00" />
		<column name="day26" type="number" default="00" />
		<column name="day27" type="number" default="00" />
		<column name="day28" type="number" default="00" />
		<column name="day29" type="number" default="00" />
		<column name="day30" type="number" default="00" />
		<column name="day31" type="number" default="00"  />
		<column name="daysum02" type="number"  default="00" />
		<column name="daysum" type="number" default="00" />
		<column name="sumhour" type="number" default="00" />
		<column name="overtimehour" type="number" default="00" />
		<column name="nighthour" type="number" default="00" />
		<column name="holidayhour" type="number" default="00" />
		<column name="otherhour" type="number" default="00" />
		<column name="bulletins" type="number" default="00" />
		<column name="holiday" type="number" default="00" />
		<column name="nholiday" type="number"  default="00"/>
		<column name="other" type="number" default="00" />
		<column name="holidays" type="number" default="00" />	
		<column name="status" type="number" default="00" />
		<column name="change_woker" type="number" default="00" />
		<column name="change_date" type="date" />
		<column name="approve" type="number" default="00"/>
		<column name="approve_date" type="date" />
		<column name="org"  type="number" default="00"/>
	</history>
	<sequence  name="library" />
	<histsequence  name="sqs_table_hist" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/hrs_overtime_alerts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="hrs_overtime_alerts">
	<column name="id" type="number" null="n" />
	<column name="worker" type="number" null="n" />
	<column name="type" type="number" null="n" />
	<column name="start_date" type="date" />
	<column name="end_date" type="date" />
	<column name="day_count" type="number" null="n"  default="00" />
	<column name="info" type="varchar2" length="4000"  />
	<column name="status" type="number" null="n" />
	<column name="resolution" type="number" null="n" />
	<column name="user_approve" type="number" null="n" />
	<column name="user_approve_date" type="date" />
	<column name="chief_approve" type="number" null="n" />
	<column name="chief_approve_date" type="date" />
	<column name="del_user" type="number" null="n"  />
	<column name="del_date" type="date" />
	<column name="create_user" type="number" null="n"  />
	<column name="create_date" type="date" />
	<column name="client_id" type="number" default="00" />
	<column name="modify_user" type="number" />
	<column name="modify_date" type="date" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/lib_standard_graphs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="lib_standard_graphs" history="yes">
	<columns>
		<column name="id" type="number" null="n" />
		<column name="lib_title" type="varchar2" length="500" Ti="1" />
		<column name="lib_desc" type="varchar2" length="4000"/>
		<column name="active" type="number" null="n" />
		<column name="monday" type="number" />
		<column name="tuesday" type="number" />
		<column name="wednesday" type="number" />
		<column name="thursday" type="number" />
		<column name="friday" type="number" />
		<column name="saturday" type="number" />
		<column name="sunday" type="number" />
		<column name="client_id" type="number" default="00" />
		<column name="checksum" type="varchar2" length="4000"/>
	     <column name="modify_user" type="number" />
          <column name="modify_date" type="date" />
     </columns>
	<history>
		<column name="lib_title" type="varchar2" length="500" />
		<column name="lib_desc" type="varchar2" length="4000"/>
		<column name="active" type="number" null="n" />
		<column name="monday" type="number" />
		<column name="tuesday" type="number" />
		<column name="wednesday" type="number" />
		<column name="thursday" type="number" />
		<column name="friday" type="number" />
		<column name="saturday" type="number" />
		<column name="sunday" type="number" />
		<column name="checksum" type="varchar2" length="4000"/>
	     <column name="modify_user" type="number" />
          <column name="modify_date" type="date" />
     </history>
	<sequence  name="library" />
	<histsequence  name="sqs_standard_graphs_hist" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/hrs_sub_graph.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="hrs_sub_graph" history="yes">
	<columns>
		<column name="worker" type="number" null="n" />
		<column name="real_date" type="date" />
		<column name="rest_time" type="number" default="00"   />
		<column name="work_time" type="number" default="00"   />
		<column name="lateness" type="number" default="00"   />
		<column name="night_hours" type="number" default="00"   />
		<column name="holiday_hours" type="number" default="00"   />
	</columns>
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/system_sms_log.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="system_sms_log">
	<column name="log_date" type="date" />
	<column name="log_phone" type="varchar2" length="40" />
	<column name="log_msg" type="varchar2" length="4000" />
	<column name="log_result" type="varchar2" length="4000" />
	<column name="log_id" type="number"  />
	<column name="log_reference" type="varchar2" length="4000" />
	<column name="log_status" type="varchar2" length="400" />
	<column name="log_status_data" type="varchar2" length="4000" />
	<column name="log_status_date" type="date" />
	<column name="client_id" type="number" default="00" />
</table>
