=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/defines/xml/table.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//Kevlishvili//TABLE//EN
    SYSTEM ID: http://web.magti.ge/pda/defines/xml/table.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">

    <table>
    ...
    </table>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT table (column)*>
<!ATTLIST table
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT column EMPTY>
<!ATTLIST column
    comment CDATA #IMPLIED
    default CDATA #IMPLIED
    length CDATA #IMPLIED
    null CDATA #IMPLIED
    type CDATA #IMPLIED
    name CDATA #IMPLIED
  >

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/hrs_transported_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="hrs_transported_data">
	<column name="id" type="varchar2" length="50" />
	<column name="rec_date" type="date" />
	<column name="access_point_code" type="varchar2" length="50" />
	<column name="card_id" type="varchar2" length="4000" />
	<column name="user_id" type="number" />
	<column name="door_type" type="number" />
	<column name="cardname"  type="varchar2" length="4000" />
	<column name="parent_id" type="number" />
	<column name="client_id" type="number" default="00" />
	<column name="time_id" type="number" default="00" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/lib_f_accuracy_periods.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Created by Irakli Gzirishvili 28-10-2021-->
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="lib_f_accuracy_periods" history="yes">
	<columns>
		<column name="id" type="number" null="n" />
		<column name="lib_title" type="varchar2" length="500" Ti="1" />
		<column name="lib_desc" type="varchar2" length="4000" />
		<column name="active" type="number" null="n" default="1" />
		<column name="ordering" type="number" null="n" default="999" />
		<column name="client_id" type="number"  default="00"/>

		<column name="PERIOD_TYPE" type="number" />
		<column name="WEEK_START" type="number" />
		<column name="START_DATE_OF_MONTH" type="number" />
		<column name="FISRT_PERIOD_START" type="number" />
		<column name="SECOND_PERIOD_START" type="number" />
		<column name="START_DATE_OF_YEAR_DAY" type="number" />
		<column name="START_DATE_OF_YEAR_MONTH" type="number" />
		<column name="PERIOD_GENERATOR" type="number" />

		<column name="modify_user" type="number" />
		<column name="modify_date" type="date" />
		
		<column name="PERIOD_START" type="number"/>
		<column name="YEARLY_DAY_PERIOD_START" type="number"/>
		<column name="FIRST_PERIOD_START" type="number"/>
		<column name="FIRST_QUARTER_OF_YEAR_MONTH" type="number"/>
		<column name="SECOND_QUARTER_OF_YEAR_MONTH" type="number"/>
		<column name="THIRD_QUARTER_OF_YEAR_MONTH" type="number"/>
		<column name="FOURTH_QUARTER_OF_YEAR_MONTH" type="number"/>
		<column name="NAME_OF_YEAR_MONTH" type="number"/>
		<column name="QUARTER_DAY_START" type="number"/>
	</columns>
	<sequence  name="sqs_f_accuracy_periods" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/hrs_tasks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="hrs_tasks" history="yes">
	<columns>
		<column name="task_id" type="number" />
		<column name="lib_task_id" type="number" />
		<column name="workflow_id" type="number" />
		<column name="task_title" type="varchar2" length="4000" />
		<column name="task_description" type="varchar2" length="4000" />
		<column name="task_create_date" type="date" />
		<column name="task_due_date" type="date" />
		<column name="task_complete_date" type="date" />
		<column name="task_complete_result" type="varchar2" length="4000" />
		<column name="task_actor" type="number" />
		<column name="task_actor_group" type="number" />	
		<column name="state" type="number" />
		<column name="modify_user" type="number" />
		<column name="modify_date" type="date" />
	</columns>
	<history>
		<column name="task_id" type="number" />
		<column name="lib_task_id" type="number" />
		<column name="workflow_id" type="number"  />
		<column name="task_title" type="varchar2" length="4000" />
		<column name="task_description" type="varchar2" length="4000" />
		<column name="task_create_date" type="date" />
		<column name="task_due_date" type="date" />
		<column name="task_complete_date" type="date" />
		<column name="task_complete_result" type="varchar2" length="4000" />
		<column name="task_actor" type="number" />
		<column name="task_actor_group" type="number" />
		<column name="state" type="number" />
		<column name="modify_user" type="number" />
		<column name="modify_date" type="date" />
	</history>
	<sequence  name="procedures" />
	<histsequence  name="sqs_tasks_hist" />
	<primarykey  name="task_id" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/lib_drivers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://apps.magticom.ge/pda/defines/xml/table.dtd">
<table name="lib_drivers">
	<column name="id" type="number" null="n" />
	<column name="worker" type="number" null="n" default="00" />
	<column name="lib_desc" type="varchar2" length="4000" />
	<column name="active" type="number" null="n" default="1" />
	<column name="client_id" type="number" default="00" />
	<column name="modify_user" type="number" />
	<column name="modify_date" type="date" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/lib_f_salary_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Created by Irakli Gzirishvili 28-10-2021-->
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="lib_f_salary_types" history="yes">
	<columns>
		<column name="id" type="number" null="n" />
		<column name="lib_title" type="varchar2" length="500" Ti="1" />
		<column name="lib_desc" type="varchar2" length="4000" />
		<column name="active" type="number" null="n" default="1 " />
		<column name="ordering" type="number" null="n" default="999" />
		<column name="client_id" type="number" default="00" />
		
		<column name="payment_type" type="number" default="00"/>
<!--		<column name="gross_net" type="number" default="00"/>-->
		<column name="accuracy_period" type="number" default="00"/>
		<column name="taxes_yn" type="number"/>
	     <column name="modify_user" type="number" />
          <column name="modify_date" type="date" />
     </columns>
	<sequence  name="sqs_f_salary_types" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/lib_techinventar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://apps.magticom.ge/pda/defines/xml/table.dtd">
<table name="lib_techinventar" history="yes">
	<columns>
		<column name="id" type="number" null="n" />
		<column name="lib_title" type="varchar2" length="4000" Ti="1" />
		<column name="lib_desc" type="varchar2" length="4000" Ti="1"/>
		<column name="item_working_principes" type="varchar2" length="4000"/>
		<column name="intolerable" type="varchar2" length="4000"/>
		<column name="item_location" type="varchar2" length="4000"/>
		<column name="active" type="number" null="n" default="1" />
		<column name="ordering" type="number" />
		<column name="create_user" type="number" />
		<column name="create_date" type="number" />
		<column name="modify_user" type="number" />
		<column name="modify_date" type="date" />
		<column name="workingorder" type="varchar2" length="4000" Ti="1"/>
		<column name="safety" type="varchar2" length="4000"/>
		<column name="maintenance_start" type="date" />
		<column name="maintenance_repeat" type="number" />
     </columns>
	<history>
		<column name="lib_title" type="varchar2" length="4000" Ti="1" />
		<column name="lib_desc" type="varchar2" length="4000" Ti="1"/>
		<column name="item_working_principes" type="varchar2" length="4000"/>
		<column name="intolerable" type="varchar2" length="4000"/>
		<column name="item_location" type="varchar2" length="4000"/>
		<column name="active" type="number" null="n" default="1" />
		<column name="ordering" type="number" />
		<column name="workingorder" type="varchar2" length="4000" Ti="1"/>
		<column name="safety" type="varchar2" length="4000"/>
		<column name="maintenance_start" type="date"/>
		<column name="maintenance_repeat" type="number" />
	</history>
	<sequence  name="library" />
	<histsequence  name="sqs_cars_hist" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/hrs_decret_hour.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="hrs_decret_hour" history="yes">
	<columns>
		<column name="id" type="number" null="n" />
		<column name="worker" type="number" null="n" />
		<column name="type" type="number" null="n" />
		<column name="start_date" type="date" />
		<column name="end_date" type="date" />
		<column name="rec_date" type="date" />
		<column name="status" type="number" null="n" />
		<column name="approve" type="number" null="n" />
		<column name="approve_date" type="date" />
		<column name="del_user" type="number" null="n"  />
		<column name="del_date" type="date" />
		<column name="ucomment" type="varchar2" length="4000"  />
		<column name="client_id" type="number" default="00" />
	</columns>
	<history>
		<column name="worker" type="number" null="n" />
		<column name="type" type="number" null="n" />
		<column name="start_date" type="date" />
		<column name="end_date" type="date" />
		<column name="rec_date" type="date" />
		<column name="status" type="number" null="n" />
		<column name="approve" type="number" null="n" />
		<column name="approve_date" type="date" />
		<column name="del_user" type="number" null="n"  />
		<column name="del_date" type="date" />
		<column name="ucomment" type="varchar2" length="4000"  />
	</history>
	<sequence  name="sqs_applications" />
	<histsequence  name="sqs_decret_hour_hist" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/news.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="news">
	<column name="id" type="number" null="n" />
	<column name="title"  type="varchar2" length="4000" Ti="1" />
	<column name="introtext"  type="varchar2" length="4000" />
	<column name="text0"  type="varchar2" length="4000" />
	<column name="text1"  type="varchar2" length="4000" />
	<column name="text2"  type="varchar2" length="4000" />
	<column name="text3"  type="varchar2" length="4000" />
	<column name="text4"  type="varchar2" length="4000" />
	<column name="text5"  type="varchar2" length="4000" />
	<column name="text6"  type="varchar2" length="4000" />
	<column name="text7"  type="varchar2" length="4000" />
	<column name="text8"  type="varchar2" length="4000" />
	<column name="text9"  type="varchar2" length="4000" />
	<column name="modify_date" type="date" />
	<column name="modify_user" type="number" />
	<column name="publish_date" type="date" />
	<column name="unpublish_date" type="date" />
	<column name="image"  type="varchar2" length="4000" />
	<column name="active" type="number" />
	<column name="record_date" type="date" />
	<column name="client_id" type="number" default="00" />
</table>
