=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/defines/xml/table.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//Kevlishvili//TABLE//EN
    SYSTEM ID: http://web.magti.ge/pda/defines/xml/table.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">

    <table>
    ...
    </table>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT table (column)*>
<!ATTLIST table
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT column EMPTY>
<!ATTLIST column
    comment CDATA #IMPLIED
    default CDATA #IMPLIED
    length CDATA #IMPLIED
    null CDATA #IMPLIED
    type CDATA #IMPLIED
    name CDATA #IMPLIED
  >

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/slf_daily_salary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Created by Irakli Gzirishvili 28-10-2021-->
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="slf_daily_salary" history="yes">
	<columns>
		<column name="id" type="number" null="n"/>
		<column name="worker" type="number"  default="00"/>
		<column name="period_id" type="number"/>
		<column name="salary_type" type="number"/>
		<column name="payment_type" type="number"/>
		<column name="salary" type="number"/>
		<column name="taxes_yn" type="number"/>
		<column name="pay_pension" type="number"/>
		<column name="salary_sum" type="number"  default="00"/>
		<column name="rec_date" type="date"/>
		<column name="status" type="number"/>
		<column name="change_user" type="number"/>
		<column name="change_date" type="number"/>
		<column name="data_day" type="date"/>

		<!--Generated Columns-->
		<column name="g_net" type="number"/>
		<column name="g_income_tax" type="number"/>
		<column name="g_pension_person" type="number"/>
		<column name="g_pension_org" type="number"/>
		<column name="org" type="number"/>
		<column name="sheet_id" type="number"/>
		<column name="gen_hash" type="varchar2" length="500" />
	</columns>
	<sequence  name="sqs_daily_salary" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/hrs_workflow_log.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="hrs_workflow_log">
	<columns>
		<column name="log_flow" type="number" />
		<column name="log_task" type="number" />
		<column name="log_type" type="varchar2" length="100" />
		<column name="log_title" type="varchar2" length="4000" />
		<column name="log_user" type="number" />
		<column name="log_date" type="date" />
		<column name="log_id" type="number" />
		<column name="modify_user" type="number" />
		<column name="modify_date" type="date" />
	</columns>
	<sequence name="sqs_workflow_log" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/lib_app_flows.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Created by Irakli Gzirishvili 28-10-2021-->
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="lib_app_flows" history="yes">
	<columns>
		<column name="id" type="number" null="n" />
		<column name="app_type" type="number" null="n" />
		<column name="lib_title" type="varchar2" length="500" />
		<column name="lib_desc" type="varchar2" length="4000" />
		<column name="ordering" type="number" null="n" />
		<column name="active" type="number" null="n" />
	     <column name="modify_user" type="number" />
          <column name="modify_date" type="date" />
     </columns>
	<history>
		<column name="app_type" type="number" null="n" />
		<column name="lib_title" type="varchar2" length="500" />
		<column name="lib_desc" type="varchar2" length="4000" />
		<column name="ordering" type="number" null="n" />
		<column name="active" type="number" null="n" />
	     <column name="modify_user" type="number" />
          <column name="modify_date" type="date" />
     </history>
	<sequence  name="sqs_lib_app_flows" />
	<histsequence  name="sqs_app_flows_hist" />
</table>

=== JabaKhizanishvili/newproject/sms merge/self.ge-d-TestBranch/tables/xml/lib_f_benefits.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Created by Irakli Gzirishvili 28-10-2021-->
<!DOCTYPE table SYSTEM "http://web.magti.ge/pda/defines/xml/table.dtd">
<table name="lib_f_benefits" history="yes">
	<columns>
		<column name="id" type="number" null="n" />
		<column name="lib_title" type="varchar2" length="500" Ti="1" />
		<column name="lib_desc" type="varchar2" length="4000" />
		<column name="active" type="number" null="n" default="1 " />
		<column name="ordering" type="number" null="n" default="999" />
		<column name="client_id" type="number" default="00" />
		
		<column name="accounting_code" type="varchar2" length="500" />
		<column name="fields" type="varchar2" length="500" />
		<column name="modify_user" type="number" />
		<column name="modify_date" type="date" />

		<column name="IDENTIFIER" type="number" />
		<column name="BENEFIT_END_DATE" type="number" />
	</columns>
	<sequence  name="sqs_f_benefits" />
</table>
